// <auto-generated />
using System;
using DicomTool.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DicomTool.Shared.Migrations
{
    [DbContext(typeof(DicomDbContext))]
    [Migration("20260807115813_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DicomTool.Shared.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("DicomTool.Shared.Entities.UserSeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("SeriesDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeriesInstanceUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeriesNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserStudyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.HasIndex("SeriesInstanceUid")
                        .IsUnique();

                    b.HasIndex("UserStudyId");

                    b.ToTable("user_series", (string)null);
                });

            modelBuilder.Entity("DicomTool.Shared.Entities.UserSop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstanceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReadByUserId")
                        .HasColumnType("text");

                    b.Property<string>("SopInstanceUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserSeriesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsRead");

                    b.HasIndex("Order");

                    b.HasIndex("SopInstanceUid")
                        .IsUnique();

                    b.HasIndex("UserSeriesId");

                    b.ToTable("user_sop", (string)null);
                });

            modelBuilder.Entity("DicomTool.Shared.Entities.UserStudy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessionNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BodyPartExamined")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StudyDate")
                        .HasColumnType("date");

                    b.Property<string>("StudyDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccessionNumber");

                    b.HasIndex("Order");

                    b.HasIndex("PatientId");

                    b.HasIndex("StudyDate");

                    b.HasIndex("StudyInstanceUid")
                        .IsUnique();

                    b.HasIndex("PatientId", "StudyDate");

                    b.ToTable("user_study", (string)null);
                });

            modelBuilder.Entity("DicomTool.Shared.Entities.UserSeries", b =>
                {
                    b.HasOne("DicomTool.Shared.Entities.UserStudy", "Study")
                        .WithMany("Series")
                        .HasForeignKey("UserStudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("DicomTool.Shared.Entities.UserSop", b =>
                {
                    b.HasOne("DicomTool.Shared.Entities.UserSeries", "Series")
                        .WithMany("Sops")
                        .HasForeignKey("UserSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("DicomTool.Shared.Entities.UserSeries", b =>
                {
                    b.Navigation("Sops");
                });

            modelBuilder.Entity("DicomTool.Shared.Entities.UserStudy", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
